Часть 5: Тестирование контроллеров
carboninc/QnA pull request #2
Opened 2018-12-14 09:42 UTC by carboninc

2018-12-15 03:27 UTC, vkurennov requested changes

2018-12-15 03:27 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer = question.answers.new(answer_params)
Тут конфликт имен получается. Ты используешь здесь локальную переменную, а далее, вызывая answer - отрабатывает метод из expose. Чтобы все работало корректно, нужно здесь присваивать переменную `@exposed_answer`

2018-12-15 03:27 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to assigns(:answer)
decent_expose использует не стандартные имена переменных, т.е. у тебя нет в контроллере переменной @answer, к которой ты здесь обращаешься (а assigns обращается именно к переменным, а не к методам), зато есть` @exposed_answer`, вот ее тут и надо использовать, тогда все будет работать как надо.

2018-12-17 06:35 UTC, carboninc commented on app/controllers/answers_controller.rb
> +    answer = question.answers.new(answer_params)
`@exposed_answer` самое печальное, что об этом говорилось в самом начале документации, но я этого не заметил =(

2018-12-17 06:36 UTC, carboninc commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to assigns(:answer)
Не помогло, но я нашел ошибку, неправильно настроенные роуты

2018-12-17 09:45 UTC, vkurennov approved these changes

2018-12-17 09:45 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @exposed_answer.save
Тут уже к answer обращайся, т.е. к методу, иначе какой смысл в использовании гема, если все равно с переменными работаем напрямую?

2018-12-17 09:45 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, :invalid) } }.to_not change(question.answers, :count)
Вот здесь просто Answer должен быть в change, т.к. важно проверить, что в принципе не создан никакой ответ.

2018-12-17 11:02 UTC, merged