Часть 6: Интеграционное (acceptance) тестирование
carboninc/QnA pull request #3
Opened 2018-12-20 05:47 UTC by carboninc

…n Login | Only An Authenticated User Can Create Questions

2018-12-21 14:14 UTC, vkurennov requested changes

2018-12-21 14:14 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.destroy
Нужна проверка на автора на уровне контроллера, обойти виды слишком легко, сделав прямой запрос

2018-12-21 14:14 UTC, vkurennov commented on app/controllers/questions_controller.rb
>    def destroy
Тут тоже нужна проверка на автора

2018-12-21 14:14 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  - if current_user.author?(answer)
Если юзер не залогинен, то здесь будет ошибка, т.к.  current_user вернет nil, используй [safe navigation](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), чтобы этого избежать.

2018-12-21 14:14 UTC, vkurennov commented on app/views/layouts/application.html.slim
> +    - if user_signed_in?
Хорошо бы ссылку на логин добавить, если юзер не залогинен

2018-12-21 14:14 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Сразу напишу: когда добавишь проверку на автора в контроллер, тут нужно будет тестировать оба варианта и для автора и для не-автора, лучше всего разнести тесты по контекстам

2018-12-21 14:14 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
См. замечания к аналогичным тестам в контроллере ответов

2018-12-21 14:14 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +  scenario 'User trying to delete is not your answer' do
Нужен похожий тест для незалогиненного юзера

2018-12-21 14:14 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +  scenario 'User trying to delete is not your question' do
Нужен похожий тест для незалогиненного юзера

2018-12-21 14:14 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А где тесты нам метод `author?`? Любой код, который ты пишешь нужно покрывать тестами, а в идеале - начинать с тестов перед тем, как собрался писать какой-либо код

2018-12-21 15:34 UTC, carboninc commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
Я это уже понял ) я написал сперва логику, потом тесты и пожалел об этом )

2018-12-24 10:51 UTC, vkurennov approved these changes

2018-12-24 10:51 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'Not author tries' do
А какой в этом контексте рендер/редирект?

2018-12-24 10:51 UTC, vkurennov commented on spec/models/user_spec.rb
> +  it 'User is author of answer' do
Не нужно на разных объектах проверять, у тебя же универсальный метод. Достаточно на любом одном типе аргумента проверить

2019-01-08 06:29 UTC, merged